---
functional:
  - пользователь может зарегистрироваться используя логин и пароль
  - пользователь может авторизваться через через github
  - пользователь может авторизваться через через discord
non-functional:
  - все страницы сайта быстро открываются страницы
  - закрыв страницу, после начала битвы, можно вернуться в нее
implicit:
  - сайт работает по протоколу htpps
  - персональные данные пользователя защищены
