---
functional:
  # функции доступные до авторизации
  - Пользователь может протестировать механику сражения, не заходя в аккаунт

  # регистрация и авторизация
  - Пользователь может зарегистрироваться используя логин и пароль
  - Пользователь может зарегистрироваться через свой аккаунт на github'e
  - Пользователь может зарегистрироваться через свой аккаунт в discord'e
  - Пользователь может авторизоваться через свои логин и пароль
  - Пользователь может авторизоваться через свой аккаунт на github'e
  - Пользователь может авторизоваться через свой аккаунт в discord'e
  - Пользователь может восстановить свой пароль
  - Пользователь может выйти из своего аккаунта 

  # действия в личном кабинете
  - Пользователь может зайти в подробности о своем профиле
  - Пользователь может изменить свой никнейм 
  - Пользователь может сменить язык сайта на английский
  - Пользователь может сменить язык сайта на русский
  - Пользователь может сменить язык программирования по умолчанию в битве 
  - Пользователь может выбрать один из типов звуков
  - Пользователь может выбрать громкость звука в обычной битве
  - Пользователь может выбрать громкость звука в турнире 
  - Пользователь может привязать свой аккаунт на гитхаб
  - Пользователь может привязать свой аккаунт в дискорде

  # действия с кланами
  - Пользователь может создать клан
  - Пользователь может вступить в клан
  - Пользователь может посмотреть информацию о созданных кланах 

  # действия из лобби
  - Пользователь может написать в общий чат на главной странице
  - Пользователь может присоединиться к битве с ботом 
  - Пользователь может присоединиться к созданной битве с человеком
  - Пользователь может подключиться как зритель к битве, которая уже началась
  - Пользователь может посмотреть историю контестов
  - Пользователь может посмотреть историю созданных им турниров 
  - Пользователь может создать свой турнир с ... (короче может)
  - Пользователь может перейти к репозиторию, где находится открытый исходный сайт приложения
  - Пользователь может перейти к на сайт hexlet'a
  - Пользователь может перейти в телеграм чат, посвященный поддержке сайта codebattle
  - Пользователь может перейти в дискорд чат, посвященный поддержке сайта codebattle

  # взаимодействия с другими пользователями
  - Пользователь может посмотреть подробную информацию о другом пользователе
  - Пользователь может перейти в аккаунт гитхаба другого пользователя 
  - Пользователь может написать в личные сообщения другому пользователю 
  - Пользователь может присоединиться к созданной битве по ссылке-приглашению
  - Пользователь может принять отправленное приглашение на битву через интерфейс сайта
  - Пользователь может отклонить отправленное приглашение на битву через интерфейс сайта

  # пак с задачами
  - Пользователь может посмортеть список всех задач, доступных на сайте
  - Пользователь может создать свой пак с задачами 
  - Пользователь может отдельно посмотреть подробную информацию по каждой задаче
  - Пользователь может запустить задачу из раздела подробной информации о задаче
  - Пользователь может посмотреть топ 10 самых быстрых решений конкретной задачи

  # все, что касается создание битвы
  - Пользователь может сам создать сражение
  - Пользователь выбирает уровень сложности задания при создании битвы
  - Пользователь выбирает, как будет подобран соперник (ожидать присоединения соперника, кинуть приглашение, игра с ботом) при создании битвы
  - Пользователь выбирает лимит времени на решение задачи при создании битвы
  - Пользователь может выбрать случайное задание при создании битвы
  - Пользователь может выбрать конкретное задание при создании битвы
  - Пользователь может выбрать класс задач, к которому относится задание на битву  

  # во время битвы
  - Пользователь может выбрать описание задачи на русском языке
  - Пользователь может выбрать описание задачи на английском языке
  - Пользователь может развернуть описание задания 
  - Пользователь может сменить язык программирования для решения задачи 
  - Пользователь может включить работу редактора в режиме "vim"
  - Пользователь может выключить работу редактора в режиме "vim"
  - Пользователь может отправить свое решение на проверку
  - Пользователь может сбросить свое решение 
  - Пользователь может сдаться 
  - Пользователь может писать в чат своему оппоненту 
  - Пользователь может посмотреть запись экрана через видеоплеер битвы, в которой он участвует
  - Пользователь может дать обратную связь разработчикам по заданию
  - Пользователь может взять реванш после поражения 

  # турниры
  - Пользователь может посмотреть информацию о завершенных турнирах 
  - Пользователь может присоединиться к турниру
  - Пользователь может покинуть турнир 
  - Пользователь может писать в чат турнира
  - Пользователь, создавший турнир может перезапустить турнир 
  - Пользователь, создавший турнир может отменить турнир
  - Пользователь, создавший турнир может изменить параметры турнира 
  - Пользователь, создавший турнир может посмотреть детали турнира 
  - Пользователь, создавший турнир может исключить участника
  - Пользователь, создавший турнир может начать турнир
  - Пользователь, создавший турнир может завершить раунд
  - Пользователь, создавший турнир может завершить турнир

  # зал славы
  - Пользователь может посмотреть зал славы
  - Пользователь может посмотреть рейтинги игроков в конкретном сезоне 
  - Пользователь может посмотреть статистику конкретного игрока, принимавшего участие в сезоне 
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен сохраненят код редактора, при покидании битвы 
  
implicit:
  - Сайт не нарушает законы РФ
  - Игрок может не может редактировать чужой код в битве
  - Компиляторы, обрабатывающие код решения задания работают без оишбок
  - Система подсчета рейтинга справедливая 
  - Тесты для проверки заданий не содержат ошибок 
  - Игрокам ясно дается понять исход битвы
  - Система фиксирует каждый результат битвы (победа / поражение / ничья) 
  - Валидация надежности пароля при регистрации
  - Валидация email при регистрации
  - Валидация никнейма при регистрации
  - Бот может решить любую задачу из списка задач
